CREATE OR REPLACE PACKAGE BODY PA_ADMINISTRADOR IS
PROCEDURE INSERTAR_PRODUCTOS(XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE, XCATEGORIA IN PRODUCTOS.CATEGORIA%TYPE, XMARCA IN PRODUCTOS.MARCA%TYPE)
IS
BEGIN
INSERT INTO PRODUCTOS VALUES(NULL,XCANTIDAD,XPRECIO,XCATEGORIA,XMARCA);
END INSERTAR_PRODUCTOS;
PROCEDURE BORRAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE)
IS 
BEGIN
DELETE FROM PRODUCTOS WHERE NUMERO = XNUMERO;
END BORRAR_PRODUCTOS;
PROCEDURE ACTUALIZAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE, XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE)
IS
BEGIN
UPDATE PRODUCTOS SET CANTIDAD=XCANTIDAD 
WHERE NUMERO = XNUMERO;
END ACTUALIZAR_PRODUCTOS;
PROCEDURE INSERTAR_DESCRIPCIONES(XDETALLE IN DESCRIPCIONES.DETALLE%TYPE, XPRODUCTO IN DESCRIPCIONES.PRODUCTO%TYPE)
IS
BEGIN
INSERT INTO DESCRIPCIONES VALUES(NULL,XDETALLE,XPRODUCTO);
END INSERTAR_DESCRIPCIONES;
PROCEDURE BORRAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE)
IS 
BEGIN
DELETE FROM DESCRIPCIONES WHERE NUMERO=XNUMERO;
END BORRAR_DESCRIPCIONES;
PROCEDURE ACTUALIZAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE, XDETALLE IN DESCRIPCIONES.DETALLE%TYPE)
IS 
BEGIN
UPDATE DESCRIPCIONES SET DETALLE = XDETALLE
WHERE NUMERO = XNUMERO;
END ACTUALIZAR_DESCRIPCIONES;
END;
/
CREATE OR REPLACE PACKAGE BODY PA_PROOVEDORES IS
    PROCEDURE AD_DESPACHOS(XFECHAENVIO IN DESPACHOS.FECHAENVIO%TYPE, XFECHAENTREGA IN DESPACHOS.FECHAENTREGA%TYPE)
    IS
    BEGIN 
    INSERT INTO DESPACHOS VALUES (10000,XFECHAENVIO,XFECHAENTREGA);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20009,SQLERRM);
    END;
    PROCEDURE CO_DESPACHOS (C2 OUT SYS_REFCURSOR) AS
    BEGIN
    OPEN C2 FOR
    SELECT NUMERO,FECHAENVIO,FECHAENTREGA FROM DESPACHOS;
    END; 
    PROCEDURE AD_PEDIDOS(XFECHAORDEN IN PEDIDOS.FECHAORDEN%TYPE, XCANTIDADPRODUCTOS IN PEDIDOS.CANTIDADPRODUCTOS%TYPE, XPAGOREALIZADO IN PEDIDOS.PAGOREALIZADO%TYPE,XPRECIOVENTA IN NUMBER, XPROOVEDOR IN PEDIDOS.PROOVEDOR%TYPE, XDESPACHO IN PEDIDOS.DESPACHO%TYPE)
    IS 
    BEGIN
    INSERT INTO PEDIDOS VALUES (100000,XFECHAORDEN,XCANTIDADPRODUCTOS,XPAGOREALIZADO,xprecioventa,XPROOVEDOR,XDESPACHO);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20004,SQLERRM);
    END;
    PROCEDURE CO_PEDIDOS (C3 OUT SYS_REFCURSOR) AS
    BEGIN
    OPEN C3 FOR
        SELECT NUMERO,FECHAORDEN,CANTIDADPRODUCTOS,PROOVEDOR FROM PEDIDOS;
    END;
END;
/
CREATE OR REPLACE PACKAGE BODY PA_ADMIN IS
    PROCEDURE AD_DESPACHOS(XFECHAENVIO IN DESPACHOS.FECHAENVIO%TYPE, XFECHAENTREGA IN DESPACHOS.FECHAENTREGA%TYPE)
    IS
    BEGIN 
        INSERT INTO DESPACHOS VALUES (10000,XFECHAENVIO,XFECHAENTREGA);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20009,SQLERRM);
    END;
    PROCEDURE CO_DESPACHOS (C4 OUT SYS_REFCURSOR) AS
    BEGIN
    OPEN C4 FOR
        SELECT NUMERO,FECHAENVIO,FECHAENTREGA FROM DESPACHOS;
    END; 
    PROCEDURE AD_PEDIDOS(XFECHAORDEN IN PEDIDOS.FECHAORDEN%TYPE, XCANTIDADPRODUCTOS IN PEDIDOS.CANTIDADPRODUCTOS%TYPE, XPAGOREALIZADO IN PEDIDOS.PAGOREALIZADO%TYPE,XPRECIOVENTA IN NUMBER, XPROOVEDOR IN PEDIDOS.PROOVEDOR%TYPE, XDESPACHO IN PEDIDOS.DESPACHO%TYPE)
    IS 
    BEGIN
        INSERT INTO PEDIDOS VALUES (100000,XFECHAORDEN,XCANTIDADPRODUCTOS,XPAGOREALIZADO,XPRECIOVENTA,XPROOVEDOR,XDESPACHO);
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004,SQLERRM);
    END;
    PROCEDURE CO_PEDIDOS (C5 OUT SYS_REFCURSOR) AS
    BEGIN
    OPEN C5 FOR
        SELECT NUMERO,FECHAORDEN,CANTIDADPRODUCTOS,PROOVEDOR FROM PEDIDOS;
    END;
    PROCEDURE EL_DESPACHOS(XNUMERO IN NUMBER, XFECHAENVIO IN DATE,XFECHAENTREGA IN DATE)
    IS
    BEGIN
        DELETE FROM DESPACHOS
        WHERE NUMERO = XNUMERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004,SQLERRM);
    END;
    PROCEDURE AC_DESPACHOS(XNUMERO IN NUMBER,XFECHAENVIO IN DATE, XFECHAENTREGA IN DATE)
    IS
    BEGIN
        UPDATE DESPACHOS SET FECHAENVIO = XFECHAENVIO
        WHERE NUMERO = XNUMERO;
        UPDATE DESPACHOS SET FECHAENTREGA = XFECHAENTREGA
        WHERE NUMERO = XNUMERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002,SQLERRM);
    END;
    PROCEDURE EL_PEDIDOS(XNUMERO IN NUMBER, XFECHAORDEN IN DATE, XCANTIDADPRODUCTOS IN NUMBER, XPAGOREALIZADO VARCHAR2,XPRECIOVENTA IN NUMBER, XPROOVEDORE IN NUMBER, XDESPACHO NUMBER)
    IS 
    BEGIN
        DELETE FROM PEDIDOS
        WHERE NUMERO = XNUMERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20004,SQLERRM);
    END;
    PROCEDURE AC_PEDIDOS(XNUMERO IN NUMBER,XCANTIDADPRODUCTOS IN NUMBER, XPAGOREALIZADO IN VARCHAR2,XPRECIOVENTA IN NUMBER)
    IS 
    BEGIN
        UPDATE PEDIDOS SET CANTIDADPRODUCTOS = XCANTIDADPRODUCTOS
        WHERE NUMERO = XNUMERO;
        UPDATE PEDIDOS SET PRECIOVENTA = XPRECIOVENTA
        WHERE NUMERO = XNUMERO;
        UPDATE PEDIDOS SET PAGOREALIZADO = XPAGOREALIZADO
        WHERE NUMERO = XNUMERO;
    END;   
END;

