CREATE OR REPLACE PACKAGE PA_ADMINISTRADOR IS
PROCEDURE INSERTAR_PRODUCTOS(XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE, XCATEGORIA IN PRODUCTOS.CATEGORIA%TYPE, XMARCA IN PRODUCTOS.MARCA%TYPE);
PROCEDURE BORRAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE);
PROCEDURE ACTUALIZAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE, XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE);
PROCEDURE INSERTAR_DESCRIPCIONES(XDETALLE IN DESCRIPCIONES.DETALLE%TYPE, XPRODUCTO IN DESCRIPCIONES.PRODUCTO%TYPE);
PROCEDURE BORRAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE);
PROCEDURE ACTUALIZAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE, XDETALLE IN DESCRIPCIONES.DETALLE%TYPE);
END;
/
CREATE OR REPLACE PACKAGE PA_ADMIN IS
    PROCEDURE AD_DESPACHOS(XFECHAENVIO IN DESPACHOS.FECHAENVIO%TYPE, XFECHAENTREGA IN DESPACHOS.FECHAENTREGA%TYPE);
    PROCEDURE CO_DESPACHOS (C4 OUT SYS_REFCURSOR); 
    PROCEDURE EL_DESPACHOS(XNUMERO IN NUMBER, XFECHAENVIO IN DATE,XFECHAENTREGA IN DATE);
    PROCEDURE AC_DESPACHOS(XNUMERO IN NUMBER,XFECHAENVIO IN DATE, XFECHAENTREGA IN DATE);
    PROCEDURE AD_PEDIDOS(XFECHAORDEN IN PEDIDOS.FECHAORDEN%TYPE, XCANTIDADPRODUCTOS IN PEDIDOS.CANTIDADPRODUCTOS%TYPE, XPAGOREALIZADO IN PEDIDOS.PAGOREALIZADO%TYPE,XPRECIOVENTA IN NUMBER, XPROOVEDOR IN PEDIDOS.PROOVEDOR%TYPE, XDESPACHO IN PEDIDOS.DESPACHO%TYPE);
    PROCEDURE CO_PEDIDOS (C5 OUT SYS_REFCURSOR); 
    PROCEDURE EL_PEDIDOS(XNUMERO IN NUMBER, XFECHAORDEN IN DATE, XCANTIDADPRODUCTOS IN NUMBER, XPAGOREALIZADO VARCHAR2,XPRECIOVENTA IN NUMBER, XPROOVEDORE IN NUMBER, XDESPACHO NUMBER);
    PROCEDURE AC_PEDIDOS(XNUMERO IN NUMBER,XCANTIDADPRODUCTOS IN NUMBER, XPAGOREALIZADO IN VARCHAR2,XPRECIOVENTA IN NUMBER);
END;
/
CREATE OR REPLACE PACKAGE PA_PROOVEDORES IS 
    PROCEDURE AD_DESPACHOS(XFECHAENVIO IN DESPACHOS.FECHAENVIO%TYPE, XFECHAENTREGA IN DESPACHOS.FECHAENTREGA%TYPE);
    PROCEDURE CO_DESPACHOS (C2 OUT SYS_REFCURSOR); 
    PROCEDURE AD_PEDIDOS(XFECHAORDEN IN PEDIDOS.FECHAORDEN%TYPE, XCANTIDADPRODUCTOS IN PEDIDOS.CANTIDADPRODUCTOS%TYPE, XPAGOREALIZADO IN PEDIDOS.PAGOREALIZADO%TYPE,XPRECIOVENTA IN NUMBER, XPROOVEDOR IN PEDIDOS.PROOVEDOR%TYPE, XDESPACHO IN PEDIDOS.DESPACHO%TYPE);
    PROCEDURE CO_PEDIDOS (C3 OUT SYS_REFCURSOR); 
END;