CREATE OR REPLACE PACKAGE CRUD_PRODUCTOS IS
PROCEDURE INSERTAR_PRODUCTOS(XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE, XCATEGORIA IN PRODUCTOS.CATEGORIA%TYPE, XMARCA IN PRODUCTOS.MARCA%TYPE);
PROCEDURE BORRAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE);
PROCEDURE ACTUALIZAR_PRODUCTOS(XNUMERO IN PRODUCTOS.NUMERO%TYPE, XCANTIDAD IN PRODUCTOS.CANTIDAD%TYPE, XPRECIO IN PRODUCTOS.PRECIO%TYPE);
PROCEDURE CONSULTAR_PRODUCTOS(CURSOR1 OUT SYS_REFCURSOR);
PROCEDURE INSERTAR_DESCRIPCIONES(XDETALLE IN DESCRIPCIONES.DETALLE%TYPE,XPRODUCTO IN DESCRIPCIONES.PRODUCTO%TYPE);
PROCEDURE BORRAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE);
PROCEDURE ACTUALIZAR_DESCRIPCIONES(XNUMERO IN DESCRIPCIONES.NUMERO%TYPE, XDETALLE IN DESCRIPCIONES.DETALLE%TYPE);
PROCEDURE CONSULTAR_DESCRIPCIONES(CURSOR2 OUT SYS_REFCURSOR);
PROCEDURE INSERTAR_TIENE(XPEDIDO IN PERTENENCIAS.PEDIDO%TYPE,XPRODUCTO IN PERTENENCIAS.PRODUCTO%TYPE,XTAMAÑO IN PERTENENCIAS.TAMAÑO%TYPE,XCOLOR IN PERTENENCIAS.COLOR%TYPE,XAÑOPRODUCTO IN PERTENENCIAS.AÑOPRODUCTOS%TYPE);
PROCEDURE CONSULTAR_TIENE(CURSOR3 OUT SYS_REFCURSOR);
END;
/
CREATE OR REPLACE PACKAGE CRUD_PROOVEDOR IS
    PROCEDURE AD_PROOVEDORES(XTELEFONO IN PROOVEDORES.TELEFONO%TYPE, XNOMBREEMPRESA IN PROOVEDORES.NOMBREEMPRESA%TYPE, XNIT IN PROOVEDORES.NIT%TYPE, XURL IN PROOVEDORES.URL%TYPE);
    PROCEDURE MO_PROOVEDORES(XTELEFONO IN PROOVEDORES.TELEFONO%TYPE, XNOMBREEMPRESA IN PROOVEDORES.NOMBREEMPRESA%TYPE, XNIT IN PROOVEDORES.NIT%TYPE, XURL IN PROOVEDORES.URL%TYPE);
    PROCEDURE CO_PROOVEDORES(C1 OUT SYS_REFCURSOR);
    PROCEDURE EL_PROOVEDORES(XNUMERO IN PROOVEDORES.NUMERO%TYPE,XTELEFONO IN PROOVEDORES.TELEFONO%TYPE, XNOMBREEMPRESA IN PROOVEDORES.NOMBREEMPRESA%TYPE, XNIT IN PROOVEDORES.NIT%TYPE, XURL IN PROOVEDORES.URL%TYPE);
END;
/
CREATE OR REPLACE PACKAGE CRUD_DESPACHO IS
    PROCEDURE AD_DESPACHO(XFECHAENVIO IN DESPACHOS.FECHAENVIO%TYPE, XFECHAENTREGA IN DESPACHOS.FECHAENTREGA%TYPE);
    PROCEDURE CO_DESPACHOS (C2 OUT SYS_REFCURSOR); 
END;
/
CREATE OR REPLACE PACKAGE CRUD_PEDIDO IS
    PROCEDURE AD_PEDIDO(XFECHAORDEN IN PEDIDOS.FECHAORDEN%TYPE, XCANTIDADPRODUCTOS IN PEDIDOS.CANTIDADPRODUCTOS%TYPE, XPAGOREALIZADO IN PEDIDOS.PAGOREALIZADO%TYPE,XPRECIOVENTA IN NUMBER, XPROOVEDOR IN PEDIDOS.PROOVEDOR%TYPE, XDESPACHO IN PEDIDOS.DESPACHO%TYPE);
    PROCEDURE CO_PEDIDOS (C3 OUT SYS_REFCURSOR); 
END;

