---agregar
IS
	BEGIN
	INSERT INTO PRODUCTOS VALUES(NULL,XCANTIDAD,XPRECIO,XCATEGORIA,XMARCA);
	COMMIT;
	EXCEPTION
	WHEN OTHERS THEN 
	ROLLBACK;
	RAISE_APPLICATION_ERROR(-20001,SQLERRM);
	END INSERTAR_PRODUCTOS;
--eliminar
IS 
	BEGIN
	DELETE FROM PRODUCTOS WHERE NUMERO = XNUMERO;
	COMMIT;
	EXCEPTION
	WHEN OTHERS THEN 
	ROLLBACK;
	RAISE_APPLICATION_ERROR(-20002,SQLERRM);
	END BORRAR_PRODUCTOS;
--actualizar
IS
	BEGIN
	UPDATE PRODUCTOS SET CANTIDAD=XCANTIDAD, PRECIO=XPRECIO
	WHERE NUMERO = XNUMERO;
	COMMIT;
	EXCEPTION
	WHEN OTHERS THEN 
	ROLLBACK;
	RAISE_APPLICATION_ERROR(-20003,SQLERRM);
	END ACTUALIZAR_PRODUCTOS;